
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kmili
 */
public class FrmEditarPersona extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditarPersona
     */
    public FrmEditarPersona() {
        initComponents();
        cargarTabla();
        this.setLocationRelativeTo(null);
    }

    public void cargarTabla() {
        Conexion objConexion = new Conexion();
        objConexion.getConexion();
        Object[][] datos = objConexion.tablaPersonas();
        DefaultTableModel modelo = new DefaultTableModel(datos, new Object[]{"Cedula", "Nombre", "Apellidos", "Direccion", "Email", "Celular", "Contrasenia"});
        tblPersonasAdmin.setModel(modelo);
        tblPersonasAdmin.setRowSelectionInterval(0, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonasAdmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPersonasAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPersonasAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonasAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonasAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPersonasAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonasAdminMouseClicked
        String cedula = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 0).toString();
        String nombre = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 1).toString();
        String apellido = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 2).toString();
        String direccion = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 3).toString();
        String email = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 4).toString();
        String celular = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 5).toString();
        String contrasenia = tblPersonasAdmin.getValueAt(tblPersonasAdmin.getSelectedRow(), 6).toString();
        FrmEditPo frmEditPo = new FrmEditPo(cedula, nombre, apellido, direccion, email, celular, contrasenia);
        frmEditPo.setVisible(true);
    }//GEN-LAST:event_tblPersonasAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersonasAdmin;
    // End of variables declaration//GEN-END:variables
}
