
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.Image;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kmili
 */
public class FrmPersona extends javax.swing.JFrame {

    /**
     * Creates new form FrmPersona
     */
    public FrmPersona() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icono.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnAgregar = new javax.swing.JButton();
        lbCedula = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        lbContrasenia = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        lbCelular1 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JulBank v1.0");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(1, 1));
        setPreferredSize(new java.awt.Dimension(640, 600));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 210, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 210, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 210, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 210, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 210, -1));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 210, -1));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 1550, 210, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        lbCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCedula.setText("Cédula");
        getContentPane().add(lbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 20));

        lbNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNombres.setText("Nombres");
        getContentPane().add(lbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        lbApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbApellidos.setText("Apellidos");
        getContentPane().add(lbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        lbDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDireccion.setText("Dirección");
        getContentPane().add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmail.setText("Email");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        lbCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCelular.setText("Celular");
        getContentPane().add(lbCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        lbContrasenia.setText("Contraseña");
        getContentPane().add(lbContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 1560, -1, -1));

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Proyecto_sin_fondo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbCelular1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCelular1.setText("Contrasena");
        getContentPane().add(lbCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 210, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion objConexion = new Conexion();
        objConexion.getConexion();
        Persona unPersona = new Persona(txtCedula.getText(), txtNombre.getText(), txtApellidos.getText(), txtDireccion.getText(), txtEmail.getText(), txtCelular.getText(), txtContra.getText());
        //Cliente unCliente = new Cliente(String.valueOf(Math.floor(Math.random()*1000)), txtCelular.getText());
        if (objConexion.agregarPersona(unPersona) > 0) {
            JOptionPane.showMessageDialog(null, "La persona con cedula " + txtCedula.getText() + " fue agregada correctamente","",JOptionPane.INFORMATION_MESSAGE);      
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCelular1;
    private javax.swing.JLabel lbContrasenia;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContra;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
