
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.Image;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**

 * 
 * @author kmili
 */
public class FrmTrasferir extends javax.swing.JFrame {
    public String celularL;
    /**
     * Creates new form FrmConsignar
     */
    public FrmTrasferir(String celular) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarLista();
        cargarSaldoCliente(celular);
        this.celularL = celular;
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icono.png"));
        return retValue;
    }

    public void cargarLista() {
        Conexion objConexion = new Conexion();
        objConexion.getConexion();
        String[] lista = objConexion.listaClientes();

        DefaultComboBoxModel modelo = new DefaultComboBoxModel(lista);

        cbhPersonas.setModel(modelo);
        cbhPersonas.addItem("Seleccione una persona");
        cbhPersonas.setSelectedItem("Seleccione una persona");
    }

    public void cargarSaldoCliente(String celular) {
        Conexion objConexion = new Conexion();
        objConexion.getConexion();
        String saldoCliente = objConexion.getSaldoCliente(celular);
        lblSaldo.setText(saldoCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbhPersonas = new javax.swing.JComboBox<>();
        txtConsignar = new javax.swing.JTextField();
        jButtonConfirmar = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JulBank v1.0");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbhPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecione persona" }));
        cbhPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(cbhPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 204, 32));

        txtConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsignarActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 61, 204, -1));

        jButtonConfirmar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 99, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSaldo.setText(".");
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Saldo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_Consignar.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbhPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhPersonasActionPerformed
          
    }//GEN-LAST:event_cbhPersonasActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
       String arryInfo[] = cbhPersonas.getSelectedItem().toString().split("-");
       String celularSeleccionado = arryInfo[0];
       int saldoSelecionado = Integer.parseInt(arryInfo[1]);
       Conexion objConexion = new Conexion();
       objConexion.getConexion();
       int saldoTrasferir = Integer.parseInt(txtConsignar.getText());
       int saldoN = saldoSelecionado + saldoTrasferir;
       int filasAfectadas = objConexion.actualizarSaldoCliente(celularSeleccionado, saldoN);
       int saldoL = Integer.parseInt(lblSaldo.getText());
       int resta =  saldoL - saldoTrasferir;
       int filasAfectadasResta = objConexion.actualizarResta(celularL, resta);
        if (filasAfectadas > 0) {
            JOptionPane.showMessageDialog(null, "Trasferencia exitosa");
            
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void txtConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrasferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrasferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrasferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrasferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrasferir("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbhPersonas;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtConsignar;
    // End of variables declaration//GEN-END:variables
}
